supprimer:
    pattern:  /supprimer/{id}
    defaults: { _controller: fidiEcommerceBundle:Panier:supprimer }

ajouter:
    pattern:  /ajouter/{id}
    defaults: { _controller: fidiEcommerceBundle:Panier:ajouter }

panier:
    pattern:  /
    defaults: { _controller: fidiEcommerceBundle:Panier:panier }

livraison:
    pattern:  /livraison
    defaults: { _controller: fidiEcommerceBundle:Panier:livraison }
    
livraison2:
    pattern:  /livraison2
    defaults: { _controller: fidiEcommerceBundle:Panier:livraison2 }

validation:
    pattern:  /validation
    defaults: { _controller: fidiEcommerceBundle:Panier:validation }

livraisonAdresseSuppression:
    pattern:  /livraison/adresse/suppression/{id}
    defaults: { _controller: fidiEcommerceBundle:Panier:adresseSuppression }
