adminPromo:
    pattern:  /
    defaults: { _controller: fidiEcommerceBundle:PromoAdmin:index }

adminPromo_show:
    pattern:  /{id}/show
    defaults: { _controller: "fidiEcommerceBundle:PromoAdmin:show" }

adminPromo_new:
    pattern:  /new
    defaults: { _controller: "fidiEcommerceBundle:PromoAdmin:new" }

adminPromo_create:
    pattern:  /create
    defaults: { _controller: "fidiEcommerceBundle:PromoAdmin:create" }
    requirements: { _method: post }

adminPromo_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "fidiEcommerceBundle:PromoAdmin:edit" }

adminPromo_update:
    pattern:  /{id}/update
    defaults: { _controller: "fidiEcommerceBundle:PromoAdmin:update" }
    requirements: { _method: post|put }

adminPromo_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "fidiEcommerceBundle:PromoAdmin:delete" }
    requirements: { _method: post|delete }
